spring.datasource:
  url: jdbc:h2:mem:testdb
  driverClassName: org.h2.Driver
  username: sa
  password:
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

logging.level.com.jojobi: debug
